---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vsphere-influxdb-go-config
  labels:
    app.kubernetes.io/name: {{ include "vsphere-influxdb-go.name" . }}
    helm.sh/chart: {{ include "vsphere-influxdb-go.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ include "vsphere-influxdb-go.name" . }}
data:
  config.json: |-
{{ toJson .Values.config | indent 4}}
