---
{{- if not (.Values.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-influxdb-go-secret
  labels:
    app.kubernetes.io/name: {{ include "vsphere-influxdb-go.name" . }}
    helm.sh/chart: {{ include "vsphere-influxdb-go.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ include "vsphere-influxdb-go.name" . }}
type: Opaque
data:
  vsphere.username: {{ .Values.vsphere.username | b64enc }}
  vsphere.password: {{ .Values.vsphere.password | b64enc }}
  {{- if .Values.influxdb.authenticated }}
  influxdb.username: {{ .Values.influxdb.username | b64enc }}
  influxdb.password: {{ .Values.influxdb.password | b64enc }}
  {{- end }}
{{- end }}