---
{{- if not (.Values.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: aaisp2mqtt-secret
  labels:
    app.kubernetes.io/name: {{ include "aaisp2mqtt.name" . }}
    helm.sh/chart: {{ include "aaisp2mqtt.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ include "aaisp2mqtt.name" . }}
type: Opaque
data:
  aaisp.username: {{ .Values.aaisp.username | b64enc }}
  aaisp.password: {{ .Values.aaisp.password | b64enc }}
  {{- if .Values.mqtt.authenticated }}
  mqtt.username: {{ .Values.mqtt.username | b64enc }}
  mqtt.password: {{ .Values.mqtt.password | b64enc }}
  {{- end }}
{{- end }}
