{{- if not (.Values.existingSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aaisp-to-mqtt-secret
  labels:
    app.kubernetes.io/name: {{ include "aaisp-to-mqtt.name" . }}
    helm.sh/chart: {{ include "aaisp-to-mqtt.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ include "aaisp-to-mqtt.name" . }}
type: Opaque
data:
  aaisp.username: {{ .Values.aaisp.username | base64 }}
  aaisp.password: {{ .Values.aaisp.password | base64 }}
  {{- if .Values.mqtt.authenticated }}
  mqtt.username: {{ .Values.mqtt.username | base64 }}
  mqtt.password: {{ .Values.mqtt.password | base64 }}
  {{- end }}
{{- end }}